//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGHub.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGHub.Blazor.Resources.ColorStrings", typeof(ColorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fafaf0.
        /// </summary>
        public static string C0 {
            get {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e6e6d5.
        /// </summary>
        public static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #5b5b5d.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #627a77.
        /// </summary>
        public static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #699991.
        /// </summary>
        public static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #70b8ab.
        /// </summary>
        public static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
    }
}
