//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGHub.Application.Resources.NotificationStrings", typeof(NotificationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh channel {0}. Please try again.
        /// </summary>
        public static string ChannelRefreshError {
            get {
                return ResourceManager.GetString("ChannelRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed channel {0}.
        /// </summary>
        public static string ChannelRefreshSuccess {
            get {
                return ResourceManager.GetString("ChannelRefreshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting. Please try again.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file ({0}).
        /// </summary>
        public static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading file ({0}).
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log out. Please try again.
        /// </summary>
        public static string LogOutError {
            get {
                return ResourceManager.GetString("LogOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You logged out.
        /// </summary>
        public static string LogOutSuccess {
            get {
                return ResourceManager.GetString("LogOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery &quot;{0}&quot; was deleted.
        /// </summary>
        public static string LotteryDeleted {
            get {
                return ResourceManager.GetString("LotteryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery result &quot;{0}&quot; was sent to telegram channel &quot;{1}&quot;.
        /// </summary>
        public static string LotteryResultSent {
            get {
                return ResourceManager.GetString("LotteryResultSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery &quot;{0}&quot; was sent to telegram channel &quot;{1}&quot;.
        /// </summary>
        public static string LotterySent {
            get {
                return ResourceManager.GetString("LotterySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} does not exist.
        /// </summary>
        public static string MissingChannel {
            get {
                return ResourceManager.GetString("MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not find comments group of Channel &apos;{0}&apos;. If there is one send something to it or refresh channel info.
        /// </summary>
        public static string MissingCommentsGroup {
            get {
                return ResourceManager.GetString("MissingCommentsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing lottery &quot;{0}&quot;. May be it was deleted.
        /// </summary>
        public static string MissingLottery {
            get {
                return ResourceManager.GetString("MissingLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing post &quot;{0}&quot;. May be it was deleted.
        /// </summary>
        public static string MissingPost {
            get {
                return ResourceManager.GetString("MissingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;No your administrated channels detected. Go to Telegram and add &lt;a target=&quot;_blank&quot; href=&quot;https://t.me/tghub_manager_bot&quot;&gt;@tghub_manager_bot&lt;/a&gt; to any of your administrated channels&lt;/p&gt;.
        /// </summary>
        public static string NoAdministratedChannels {
            get {
                return ResourceManager.GetString("NoAdministratedChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found. Try page reload.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post &quot;{0}&quot; was deleted.
        /// </summary>
        public static string PostDeleted {
            get {
                return ResourceManager.GetString("PostDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post &quot;{0}&quot; was sent to telegram channel &quot;{1}&quot;.
        /// </summary>
        public static string PostSent {
            get {
                return ResourceManager.GetString("PostSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending. Please try again.
        /// </summary>
        public static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error submitting. Please try again.
        /// </summary>
        public static string SubmitError {
            get {
                return ResourceManager.GetString("SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unbann user. Please try again.
        /// </summary>
        public static string UnBannError {
            get {
                return ResourceManager.GetString("UnBannError", resourceCulture);
            }
        }
    }
}
