//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGHub.Application.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to this resource..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive bann.
        /// </summary>
        public static string ArchiveBann {
            get {
                return ResourceManager.GetString("ArchiveBann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned automatically due to revisited spam message limit. Spam Messages:.
        /// </summary>
        public static string AutoBannContext {
            get {
                return ResourceManager.GetString("AutoBannContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bann.
        /// </summary>
        public static string Bann {
            get {
                return ResourceManager.GetString("Bann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bann context.
        /// </summary>
        public static string BannContext {
            get {
                return ResourceManager.GetString("BannContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned at.
        /// </summary>
        public static string BannedAt {
            get {
                return ResourceManager.GetString("BannedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned spammers.
        /// </summary>
        public static string BannedSpammers {
            get {
                return ResourceManager.GetString("BannedSpammers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned to.
        /// </summary>
        public static string BannedTo {
            get {
                return ResourceManager.GetString("BannedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bann history.
        /// </summary>
        public static string BannHistory {
            get {
                return ResourceManager.GetString("BannHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bann initiator.
        /// </summary>
        public static string BannInitiator {
            get {
                return ResourceManager.GetString("BannInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attach buttons to post with several attachments. Buttons will be sent in separate post..
        /// </summary>
        public static string ButtonsWarning {
            get {
                return ResourceManager.GetString("ButtonsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create lottery.
        /// </summary>
        public static string CreateLottery {
            get {
                return ResourceManager.GetString("CreateLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Post.
        /// </summary>
        public static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit lottery.
        /// </summary>
        public static string EditLottery {
            get {
                return ResourceManager.GetString("EditLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to bann user &apos;{0}&apos;?.
        /// </summary>
        public static string EnshureBann {
            get {
                return ResourceManager.GetString("EnshureBann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unbann user &apos;{0}&apos;?.
        /// </summary>
        public static string EnshureUnbann {
            get {
                return ResourceManager.GetString("EnshureUnbann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn OFF spam-list spam filtering for channel &apos;{0}&apos;?.
        /// </summary>
        public static string EnsureListSpamOff {
            get {
                return ResourceManager.GetString("EnsureListSpamOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn ON spam-list spam filtering for channel &apos;{0}&apos;?.
        /// </summary>
        public static string EnsureListSpamOn {
            get {
                return ResourceManager.GetString("EnsureListSpamOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn OFF automatic spam filtering for channel &apos;{0}&apos;?.
        /// </summary>
        public static string EnsureOffensiveSpamOff {
            get {
                return ResourceManager.GetString("EnsureOffensiveSpamOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn ON automatic spam filtering for channel &apos;{0}&apos;?.
        /// </summary>
        public static string EnsureOffensiveSpamOn {
            get {
                return ResourceManager.GetString("EnsureOffensiveSpamOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter spam word....
        /// </summary>
        public static string EnterSpamWord {
            get {
                return ResourceManager.GetString("EnterSpamWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred. See browser dev tools for details..
        /// </summary>
        public static string ExceptionDev {
            get {
                return ResourceManager.GetString("ExceptionDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. This application may no longer respond until reloaded..
        /// </summary>
        public static string ExceptionProd {
            get {
                return ResourceManager.GetString("ExceptionProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of selected files ({0}) have invalid extension. Remove them before submit..
        /// </summary>
        public static string InvalidExtensionFiles {
            get {
                return ResourceManager.GetString("InvalidExtensionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last spam messages.
        /// </summary>
        public static string LastSpamMessages {
            get {
                return ResourceManager.GetString("LastSpamMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam-list spam filtering.
        /// </summary>
        public static string ListSpamFiltering {
            get {
                return ResourceManager.GetString("ListSpamFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found such spam words:.
        /// </summary>
        public static string ListSpamReason {
            get {
                return ResourceManager.GetString("ListSpamReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to login with another account go to Telegram app or website, find chat with Telegram service notifications and click &quot;Terminate session&quot; button..
        /// </summary>
        public static string LogoutInstruction {
            get {
                return ResourceManager.GetString("LogoutInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery.
        /// </summary>
        public static string Lottery {
            get {
                return ResourceManager.GetString("Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery isn&apos;t sent yet. Wait until it is sent or send it now..
        /// </summary>
        public static string LotteryIsNotSent {
            get {
                return ResourceManager.GetString("LotteryIsNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery is already sent.
        /// </summary>
        public static string LotteryIsSent {
            get {
                return ResourceManager.GetString("LotteryIsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end dates.
        /// </summary>
        public static string LotteryReleaseDatetime {
            get {
                return ResourceManager.GetString("LotteryReleaseDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery result.
        /// </summary>
        public static string LotteryResult {
            get {
                return ResourceManager.GetString("LotteryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery result is already sent.
        /// </summary>
        public static string LotteryResultIsSent {
            get {
                return ResourceManager.GetString("LotteryResultIsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string NavComments {
            get {
                return ResourceManager.GetString("NavComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string NavDashboard {
            get {
                return ResourceManager.GetString("NavDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotteries.
        /// </summary>
        public static string NavLotteries {
            get {
                return ResourceManager.GetString("NavLotteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string NavPosts {
            get {
                return ResourceManager.GetString("NavPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive spam filtering.
        /// </summary>
        public static string OffensiveSpamFiltering {
            get {
                return ResourceManager.GetString("OffensiveSpamFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found offensive language.
        /// </summary>
        public static string OffensiveSpamReason {
            get {
                return ResourceManager.GetString("OffensiveSpamReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is channel owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants count.
        /// </summary>
        public static string ParticipantsCount {
            get {
                return ResourceManager.GetString("ParticipantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo&amp;Video.
        /// </summary>
        public static string PhotoVideo {
            get {
                return ResourceManager.GetString("PhotoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post is already sent.
        /// </summary>
        public static string PostIsSent {
            get {
                return ResourceManager.GetString("PostIsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh from Telegram.
        /// </summary>
        public static string RefreshFromTg {
            get {
                return ResourceManager.GetString("RefreshFromTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release at:.
        /// </summary>
        public static string ReleaseAt {
            get {
                return ResourceManager.GetString("ReleaseAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Time.
        /// </summary>
        public static string ReleaseTime {
            get {
                return ResourceManager.GetString("ReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a channel.
        /// </summary>
        public static string SelectChannel {
            get {
                return ResourceManager.GetString("SelectChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files format.
        /// </summary>
        public static string SelectFileFormat {
            get {
                return ResourceManager.GetString("SelectFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Telegram now.
        /// </summary>
        public static string SendNow {
            get {
                return ResourceManager.GetString("SendNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status.
        /// </summary>
        public static string SendStatus {
            get {
                return ResourceManager.GetString("SendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spammer.
        /// </summary>
        public static string Spammer {
            get {
                return ResourceManager.GetString("Spammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam message.
        /// </summary>
        public static string SpamMessage {
            get {
                return ResourceManager.GetString("SpamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam messages.
        /// </summary>
        public static string SpamMessages {
            get {
                return ResourceManager.GetString("SpamMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam-terms list.
        /// </summary>
        public static string SpamWords {
            get {
                return ResourceManager.GetString("SpamWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Send.
        /// </summary>
        public static string StatusFailedToSend {
            get {
                return ResourceManager.GetString("StatusFailedToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR. Failed to send to Telegram. Edit to reschedule or send it with &quot;Send&quot; button click.
        /// </summary>
        public static string StatusFailedToSendDescription {
            get {
                return ResourceManager.GetString("StatusFailedToSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Scheduled.
        /// </summary>
        public static string StatusNotScheduled {
            get {
                return ResourceManager.GetString("StatusNotScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING. Instatance is NOT scheduled and will NOT be sent to Telegram at specified time. Try edit to schedule.
        /// </summary>
        public static string StatusNotScheduledDescription {
            get {
                return ResourceManager.GetString("StatusNotScheduledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string StatusScheduled {
            get {
                return ResourceManager.GetString("StatusScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled and will be sent to Telegram at specified time.
        /// </summary>
        public static string StatusScheduledDescription {
            get {
                return ResourceManager.GetString("StatusScheduledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string StatusSent {
            get {
                return ResourceManager.GetString("StatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent to Telegram.
        /// </summary>
        public static string StatusSentDescription {
            get {
                return ResourceManager.GetString("StatusSentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        public static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbann context.
        /// </summary>
        public static string UnBanContext {
            get {
                return ResourceManager.GetString("UnBanContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbanned at.
        /// </summary>
        public static string UnbannedAt {
            get {
                return ResourceManager.GetString("UnbannedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbann initiator.
        /// </summary>
        public static string UnBannInitiator {
            get {
                return ResourceManager.GetString("UnBannInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners.
        /// </summary>
        public static string Winners {
            get {
                return ResourceManager.GetString("Winners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners count.
        /// </summary>
        public static string WinnersCount {
            get {
                return ResourceManager.GetString("WinnersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
